AND-Digital-Jemison/ukraine-frontend

packages/dla-piper/src/components/home/home.js

update the text decoration color of the second button on the home page

Homepage links

---

README.md

update ReadMe with dev/staging and prod urls

update ReadMe with dev/staging and prod urls

---

frontity.settings.js
packages/dla-piper/src/components/home/home.js
packages/dla-piper/src/components/index.js
packages/dla-piper/src/components/root/root.js
packages/dla-piper/src/components/volunteer/index.js
packages/dla-piper/src/components/volunteer/volunteer.js

Created a Volunteer placeholder page. To be updated at a later date, this implementation is only for the MVP.

Volunteer Placeholder Page

---

packages/dla-piper/src/components/common/wrappers.js

update tabs content spacing and line height

DLA-66 - update tabs content spacing and line height

---

packages/dla-piper/src/components/common/button.js
packages/dla-piper/src/components/confirmation/confirmation.js

added go to home button on the confirmation page

DLA-42 - added go to home button on the confirmation page

---

packages/dla-piper/src/components/common/wrappers.js
packages/dla-piper/src/components/confirmation/confirmation.js
packages/dla-piper/src/components/volunteer/volunteer.js

add content to the volunteer page

DLA-65 - add content to the volunteer page

---

packages/dla-piper/src/components/common/languageDropdown.js
packages/dla-piper/src/components/confirmation/confirmation.js
packages/dla-piper/src/components/home/home.js
packages/dla-piper/src/components/menu/menu.js
packages/dla-piper/src/components/root/root.js
packages/dla-piper/src/components/volunteer/volunteer.js
packages/dla-piper/src/index.js

Update current language based on the language dropdown
only update language on the home page 
update tab title based on the current language
update links on volunteer and confirmation page to correct language

DLA-70 - update current language based on the selected dropdown language

---

frontity.settings.js

DLA-70 - update wordpress source url

---

packages/dla-piper/src/components/common/form/familyMemberSelector.js
packages/dla-piper/src/components/common/form/radioButtonGroup.js
packages/dla-piper/src/components/refugeeForm/refugeeForm.js
packages/dla-piper/src/components/refugeeFormSteps/additionalStep.js
packages/dla-piper/src/components/refugeeFormSteps/familyStep.js
packages/dla-piper/src/components/refugeeFormSteps/index.js
packages/dla-piper/src/components/refugeeFormSteps/travelStep.js
packages/dla-piper/src/components/refugeeFormSteps/visaStep.js
packages/dla-piper/src/components/refugeeFormSteps/whoAreYouStep.js

form submission & validation messages
fixed bugs with validation errors 
Update radio button to take an object of label and value

DLA-42 - form submission & validation messages

---

packages/dla-piper/src/components/refugeeForm/refugeeForm.js
packages/dla-piper/src/components/refugeeFormSteps/travelStep.js

handle the form submission and error handling

DLA-42 - handle the form submission and error handling

---

packages/dla-piper/src/components/root/root.js

redirect user to home page from root

DLA-73 - redirect user to home page from root

---

frontity.settings.js
packages/dla-piper/src/components/common/languageDropdown.js
packages/dla-piper/src/components/root/root.js

update home page redirect to use frontity state

update language selector

---

packages/dla-piper/src/components/common/form/datePicker.js
packages/dla-piper/src/components/common/form/inputField.js
packages/dla-piper/src/components/common/form/textArea.js

update bgcolors for:
- InputFiled
- DatePicker
- TextArea

update input bgcolors to white when not error

---

packages/dla-piper/robots.txt

add a robots file
- allow most routes
- disallow confirmation page, just a test

add robots file to site

---

packages/dla-piper/src/components/common/languageDropdown.js

add an additional translation for refugee form and confirmation pages

add additional translation for refugee form and confirmation pages

---

packages/dla-piper/src/components/common/form/textArea.js
packages/dla-piper/src/components/confirmation/confirmation.js
packages/dla-piper/src/components/refugeeForm/refugeeForm.js
packages/dla-piper/src/components/refugeeFormSteps/additionalStep.js
packages/dla-piper/src/components/refugeeFormSteps/index.js
packages/dla-piper/src/components/refugeeFormSteps/summaryStep.js

Add Summary step

---

packages/dla-piper/src/components/confirmation/confirmation.js

DLA-78 - confirmation translation

---

package-lock.json
package.json
packages/dla-piper/src/components/refugeeFormSteps/additionalStep.js
packages/dla-piper/src/server.js

add Google reCAPTCHA to last step of form

Dla 75/capcha

---

frontity.settings.js
packages/dla-piper/src/components/refugeeFormSteps/additionalStep.js
packages/dla-piper/src/components/refugeeFormSteps/familyStep.js
packages/dla-piper/src/components/refugeeFormSteps/getFormButtonLabels.js
packages/dla-piper/src/components/refugeeFormSteps/summaryStep.js
packages/dla-piper/src/components/refugeeFormSteps/travelStep.js
packages/dla-piper/src/components/refugeeFormSteps/visaStep.js
packages/dla-piper/src/components/refugeeFormSteps/whoAreYouStep.js
packages/dla-piper/src/components/volunteer/volunteer.js
packages/dla-piper/src/server.js

- Add translation for form buttons 
- Give extra width to all form buttons

Dla 77/form button translations

---

README.md
packages/dla-piper/src/components/common/form/familyMemberSelector.js

Travel form v2 & updated README file

Travel form v2

---

packages/dla-piper/src/components/refugeeForm/refugeeForm.js
packages/dla-piper/src/components/refugeeFormSteps/getFormButtonLabels.js

remember the user's last step
remove console logs

remember the user's last step

---

packages/dla-piper/src/components/common/languageDropdown.js
packages/dla-piper/src/components/notFound/notFound.js

fix redirect on the 404 and show content only when it's ready

fix redirect on the 404 and show content only when it's ready

---

packages/dla-piper/src/components/notFound/notFound.js
packages/dla-piper/src/components/refugeeFormSteps/whoAreYouStep.js

add validation message for invalid date

add validation message for invalid date
